// Soft pastel low-poly palette tuned to the concept art:
// muted greens, warm sand, pastel roofs, faceted shading.
export const palette = {
  sky: "#cfeae6",
  fog: "#d6ece8",
  water: "#7fc6d6",
  waterDeep: "#5aa9bd",
  grass: "#bcd9a0",
  grassDark: "#a6c98a",
  sand: "#ead9b0",
  path: "#e4e2dc",
  treeLeaf: "#8fc07a",
  treeLeafAlt: "#7bb56a",
  treePine: "#6fae74",
  trunk: "#9c7b54",
  roofPink: "#e7b6bc",
  roofBlue: "#aacbe0",
  roofSage: "#a9c8a6",
  wall: "#f2ead9",
  wallAlt: "#e9ddc4",
  boatHull: "#b98a55",
  boatWood: "#caa46e",
  sail: "#f4efe2",
  // Extended set for detailed props
  foam: "#eef7f4",
  waterShallow: "#9ad4dd",
  rock: "#a8a49b",
  rockDark: "#8d897f",
  reed: "#7fae62",
  reedTip: "#c9b26a",
  cloud: "#ffffff",
  buoyRed: "#d4564f",
  gull: "#f6f3ec",
  gullWing: "#c9c4b8",
  dockPost: "#8a6a45",
  hullWhite: "#f0ece0",
  hullTrim: "#5f8fa8",
  cliff: "#c7b394",
  // Lighting (warm sun / cool fill)
  sunlight: "#ffedd0",
  skyFill: "#cfe8ef",
  groundFill: "#8fae7c",
  wheat: "#e3cd8e",
  cactus: "#7fb069",
  lighthouse: "#f2ead9",
  lighthouseRed: "#d97a6c",
} as const;
